language: java
jdk:
  - openjdk11

os:
  - linux

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

before_install:
  - docker run -d -e POSTGRES_PASSWORD=$PASSCODE -e POSTGRES_USER=$USER --name postgres_container -p 5432:5432 postgres
  - curl https://raw.githubusercontent.com/enesusta/travis-test/master/auth_user.sql?token=$ACCESS_TOKEN --output data.sql
  - cat data.sql | docker exec -i postgres_container psql -U docker

install: true
#

script:
  - mvn clean verify -Dmaven.javadoc.skip=True -B -V